### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by bbhtt**
Supersedes https://github.com/flathub/org.caione.GScope/pull/4

Ping, @carlocaione, please review when you have time, thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Review by carlocaione — APPROVED** [review]
LGTM but please note that this app is basically unmaintained.

**Comment by bbhtt** [comment]
> LGTM but please note that this app is basically unmaintained.

If it works, I think it is better to keep it with an updated runtime (3.34 runtime is long EOL).

You can EOL the app if you want, as well.

**Comment by bbhtt** [comment]
Hello, any chance of merging this? Please let me know if anything else is required.

**Comment by bbhtt** [comment]
Thanks!

**Pull request merged**
